ARG ENV_REPOSITORY=pawdigital/paw-env
FROM ${ENV_REPOSITORY}:base

RUN apt-get update -qq && apt-get install -yqq \
git \
libboost-all-dev

ARG REPOSITORY=pawdigital/paw-node
LABEL org.opencontainers.image.source https://github.com/$REPOSITORY
